language: node_js
node_js:
- '0.10'
- '0.8'
env:
  matrix:
  - TEST_CMD="mocha"
  - TEST_CMD="lint"
  global:
  - secure: VRFWHz0KQonq3zeW579vB5gjy9F0ntO03BJ6T3A8Y44qdtn5+Gj5xlS3XUqhBAqAOeCWG5TDehYm7fvodEHLAecdqJ6cdygG3zISToVMoDVgzBwSXUNDgPQfSjxfSaq3OOtr3MnzK6S3K1XxVYxXtPvCCGc7QjmsihMEJ9kDYz0=
  - secure: Li0Ryb2vbg+AYXiQXaFN680hEGJxYaW8g8PJuK+isOifTEOki3NvHwHFPKpx7LuEAqqbrop7aTQ+JP8btnz3u3RirZvq5esh3RptSuu1brcNcfpmgKKQYflWPeFyqCTpQQ1TFS6Me3KoHYIrTn9naGD1bINzAAUhWa8CW8nSFis=
  - secure: MdF+hhvbQAcDEzKm+Z6RTXlSp3PfuQf05keZ+ve06IVmU7wmmfkkZxSdOMx5Cv4OytooM9I2iTWz1BWcHLcETlbCf6WAqO6SrX9j64kIHfvoX9y4GWSu5Xy3+PaXAdR01vLSUjYeiaV5d1MV+e6FKrgGMDwXJSHx4uEorP4F5PU=
before_script:
- npm install -g grunt-cli
- npm install iostreams
script:
- grunt travis
after_script:
- if [ "$TEST_CMD" = 'mocha' ]; then npm run coveralls; fi
