language: node_js
node_js:
- '0.10'
- '0.8'
env:
  matrix:
  - TEST_CMD="mocha"
  - TEST_CMD="lint"
before_script:
- npm install -g grunt-cli
- npm install iostreams
script:
- grunt travis
after_script:
- if [ "$TEST_CMD" = 'mocha' ]; then npm run coveralls; fi